/**
 * Freak In The Sheets - Referral Listings
 * UK-based premium adult store accepting crypto (BTC, ETH)
 * Real products scraped from freakinthesheets.co.uk
 */

import { Listing } from '../types';

// Image imports
import clitoralSquirrelImg from '@/assets/freakinthesheets/clitoral-squirrel.jpg';
import paddlePinkImg from '@/assets/freakinthesheets/paddle-pink.jpg';
import buttPlugBlingImg from '@/assets/freakinthesheets/butt-plug-bling.jpg';
import nippleClampsImg from '@/assets/freakinthesheets/nipple-clamps.jpg';
import miniRabbitImg from '@/assets/freakinthesheets/mini-rabbit.jpg';
import rabbitVibratorImg from '@/assets/freakinthesheets/rabbit-vibrator.jpg';
import teddyRedImg from '@/assets/freakinthesheets/teddy-red.jpg';
import laceBodysuitImg from '@/assets/freakinthesheets/lace-bodysuit.jpg';
import collarBlackImg from '@/assets/freakinthesheets/collar-black.jpg';
import lipstickVibeImg from '@/assets/freakinthesheets/lipstick-vibe.jpg';
import masturbatorImg from '@/assets/freakinthesheets/masturbator.jpg';
import prostateMassagerImg from '@/assets/freakinthesheets/prostate-massager.jpg';
import doubleDildoImg from '@/assets/freakinthesheets/double-dildo.jpg';
import cockRingsImg from '@/assets/freakinthesheets/cock-rings.jpg';
import stockingsImg from '@/assets/freakinthesheets/stockings.jpg';
import magicWandImg from '@/assets/freakinthesheets/magic-wand.jpg';
import jumpsuitImg from '@/assets/freakinthesheets/jumpsuit.jpg';
import chastityCageImg from '@/assets/freakinthesheets/chastity-cage.jpg';

const FREAK_BASE_URL = 'https://freakinthesheets.co.uk';
const GBP_TO_USD = 1.27; // Approximate conversion rate

const getProductUrl = (slug: string) => `${FREAK_BASE_URL}/product/${slug}/`;

export const freakInTheSheetsListings: Partial<Listing>[] = [
  // Top sellers
  {
    id: 'fits-001',
    title: 'Clitoral Squirrel Sucking GVibe',
    description: 'Advanced clitoral suction device with multiple intensity modes. Rechargeable, waterproof design.',
    priceUsd: 38.09,
    priceXmr: 0.23,
    category: 'adult-intimacy',
    images: [clitoralSquirrelImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('clitoral-squirrel-sucking-gvibe'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-002',
    title: 'Rouge Garments Paddle Pink',
    description: 'Premium pink leather paddle for sensual play. Durable construction with comfortable grip.',
    priceUsd: 31.74,
    priceXmr: 0.19,
    category: 'adult-intimacy',
    images: [paddlePinkImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rouge-garments-paddle-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-003',
    title: 'Anal Adventures Matrix Swirling Bling Butt Plug',
    description: 'Luxurious butt plug with sparkling crystal jewel. Smooth silicone, body-safe materials.',
    priceUsd: 26.63,
    priceXmr: 0.16,
    category: 'adult-intimacy',
    images: [buttPlugBlingImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('anal-adventures-matrix-swirling-bling-butt-plug'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-004',
    title: 'Black Nipple Clamps',
    description: 'Adjustable nipple clamps with connecting chain. Metal construction, suitable for all levels.',
    priceUsd: 35.54,
    priceXmr: 0.21,
    category: 'adult-intimacy',
    images: [nippleClampsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('black-nipple-clamps'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-005',
    title: 'Nude Hazel Mini Rabbit Massager',
    description: 'Compact dual-stimulation rabbit vibrator. Multiple modes, USB rechargeable, whisper-quiet.',
    priceUsd: 44.44,
    priceXmr: 0.27,
    category: 'adult-intimacy',
    images: [miniRabbitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('nude-hazel-mini-rabbit-massager'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-006',
    title: 'Rocks Off Flutter Rabbit Pink',
    description: 'Premium dual-stimulation rabbit vibrator with fluttering action. Waterproof, rechargeable.',
    priceUsd: 59.67,
    priceXmr: 0.36,
    category: 'adult-intimacy',
    images: [rabbitVibratorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rocks-off-flutter-rabbit-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-007',
    title: 'Le Desir Crotchless Rhinestone Teddy Red',
    description: 'Glamorous red teddy with rhinestone detailing. Crotchless design, plus sizes UK 14-20.',
    priceUsd: 24.13,
    priceXmr: 0.15,
    category: 'adult-intimacy',
    images: [teddyRedImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('le-desir-crotchless-rhinestone-teddy-red-uk-14-to-20'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-008',
    title: 'Le Desir Suspender Bodystocking',
    description: 'Elegant black bodystocking with suspender design. Stretchy fit, plus size UK 14-20.',
    priceUsd: 22.85,
    priceXmr: 0.14,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('le-desir-suspender-bodystocking-uk-14-to-20'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-009',
    title: 'Rouge Garments O-Ring Studded Collar Black',
    description: 'Black leather collar with O-ring and studded details. Adjustable, durable construction.',
    priceUsd: 30.47,
    priceXmr: 0.18,
    category: 'adult-intimacy',
    images: [collarBlackImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rouge-garments-oring-thin-studded-collar-black'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-010',
    title: 'Naughty Bits Bad Bitch Lipstick Vibrator',
    description: 'Discreet lipstick-style vibrator in elegant case. USB rechargeable, travel-friendly.',
    priceUsd: 35.54,
    priceXmr: 0.21,
    category: 'adult-intimacy',
    images: [lipstickVibeImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('naughty-bits-bad-bitch-rechargeable-lipstick-vibrator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  // Additional products continue...
  {
    id: 'fits-011',
    title: 'Long Nipple Clamps With Weight 150g',
    description: 'Weighted nipple clamps for advanced play. 150g weights provide intense sensation.',
    priceUsd: 53.33,
    priceXmr: 0.32,
    category: 'adult-intimacy',
    images: [nippleClampsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('long-nipple-clamps-with-weight-150g'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-012',
    title: 'Pipedream Extreme Flip A Sista Over Masturbator',
    description: 'Dual-entry masturbator with realistic textures. Flexible, easy-grip design.',
    priceUsd: 34.27,
    priceXmr: 0.21,
    category: 'adult-intimacy',
    images: [masturbatorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('pipedream-extreme-flip-a-sista-over-masturbator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-013',
    title: 'VacULock 8 Inch Realistic Cock Attachment',
    description: '8-inch realistic attachment for VacULock system. Flesh pink, body-safe materials.',
    priceUsd: 73.65,
    priceXmr: 0.45,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('vaculock-8-inch-realistic-cock-attachment-flesh-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-014',
    title: 'Double Mini Twin Head Jelly Penis Dildo',
    description: 'Flexible double-ended dildo. Jelly material, compact size for versatility.',
    priceUsd: 15.23,
    priceXmr: 0.09,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('double-mini-twin-head-jelly-penis-dildo'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-015',
    title: 'Top And Brief Chain Set',
    description: 'Luxurious chain lingerie set. Adjustable fit, provocative design.',
    priceUsd: 125.67,
    priceXmr: 0.76,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('top-and-brief-chain-set'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-016',
    title: 'Nexus Rev Stealth Prostate Massager',
    description: 'Premium prostate massager with remote control. Multiple vibration patterns, waterproof.',
    priceUsd: 189.15,
    priceXmr: 1.14,
    category: 'adult-intimacy',
    images: [prostateMassagerImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('nexus-rev-stealth-prostate-massager'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-017',
    title: 'Dr Skin Posable Double Dong 14 Inches',
    description: '14-inch posable double dildo. Realistic texture, bendable for different positions.',
    priceUsd: 40.63,
    priceXmr: 0.24,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('dr-skin-posable-double-dong-14-inches'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-018',
    title: 'Dr Skin Posable Double Dong 16.5 Inches',
    description: '16.5-inch extra-long posable dildo. Ultra-flexible, realistic feel.',
    priceUsd: 41.90,
    priceXmr: 0.25,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('dr-skin-posable-double-dong-16-5-inches'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-019',
    title: 'Kiiroo Feel Pocket Powerblow Masturbator',
    description: 'High-tech masturbator with app connectivity. Multiple textures, rechargeable.',
    priceUsd: 139.69,
    priceXmr: 0.84,
    category: 'adult-intimacy',
    images: [masturbatorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('kiiroo-feel-pocket-powerblow-masturbator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-020',
    title: 'CalExotics Hydro Power Stroker Blue',
    description: 'Waterproof automatic stroker. Powerful motor, multiple speeds.',
    priceUsd: 80.00,
    priceXmr: 0.48,
    category: 'adult-intimacy',
    images: [masturbatorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('calexotics-hydro-power-stroker-blue'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-021',
    title: 'Lovetoy Pinnacle Pro Tapered Squeeze Stretcher',
    description: 'Cock ring stretcher with tapered design. Comfortable fit, enhances pleasure.',
    priceUsd: 15.23,
    priceXmr: 0.09,
    category: 'adult-intimacy',
    images: [cockRingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('lovetoy-pinnacle-pro-tapered-squeeze-stretcher'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-022',
    title: 'CalExotics TriRings Set',
    description: 'Set of three cock rings in different sizes. Stretchy, comfortable silicone.',
    priceUsd: 10.15,
    priceXmr: 0.06,
    category: 'adult-intimacy',
    images: [cockRingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('calexotics-trirings-set'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-023',
    title: '10 Speed Rechargeable Magic Wand Pink',
    description: 'Classic wand massager with 10 speeds. USB rechargeable, powerful vibrations.',
    priceUsd: 31.74,
    priceXmr: 0.19,
    category: 'adult-intimacy',
    images: [magicWandImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('10-speed-rechargeable-magic-wand-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-024',
    title: 'Kiiroo APP Pro Wand Vibrator Pink',
    description: 'Smart wand vibrator with app control. Multiple patterns, long battery life.',
    priceUsd: 138.42,
    priceXmr: 0.83,
    category: 'adult-intimacy',
    images: [magicWandImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('kiiroo-app-pro-wand-vibrator-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-025',
    title: 'Warming Rotating Beads and Thrusting Rabbit',
    description: 'Advanced rabbit with warming, rotation, and thrusting. Multiple functions.',
    priceUsd: 69.84,
    priceXmr: 0.42,
    category: 'adult-intimacy',
    images: [rabbitVibratorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('warming-rotating-beads-and-thursting-rabbit-vibe'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-026',
    title: 'Svakom CICI Slim GSpot Rabbit APP Vibrator',
    description: 'App-controlled G-spot rabbit. Slim design, powerful motors.',
    priceUsd: 86.35,
    priceXmr: 0.52,
    category: 'adult-intimacy',
    images: [rabbitVibratorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('svakom-cici-slim-gspot-rabbit-app-vibrator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-027',
    title: 'Satisfyer 2 Next Generation',
    description: 'Popular clitoral pressure wave stimulator. Multiple intensities, rechargeable.',
    priceUsd: 46.98,
    priceXmr: 0.28,
    category: 'adult-intimacy',
    images: [clitoralSquirrelImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('satisfyer-2-next-generation'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-028',
    title: 'Fetish Fantasy Pogo Thruster Vibrator',
    description: 'Hands-free thrusting vibrator. Powerful motor, adjustable angle.',
    priceUsd: 137.15,
    priceXmr: 0.83,
    category: 'adult-intimacy',
    images: [rabbitVibratorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('fetish-fantasy-pogo-thruster-vibrator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-029',
    title: 'Oh My Gem Rechargeable Butt Plug',
    description: 'Vibrating butt plug with gem accent. Multiple patterns, waterproof.',
    priceUsd: 52.06,
    priceXmr: 0.31,
    category: 'adult-intimacy',
    images: [buttPlugBlingImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('oh-my-gem-rechargeable-butt-plug'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-030',
    title: 'Rimba PCage PC10 Penis Cage Pussy Pink',
    description: 'Chastity cage in pink. Secure locking system, comfortable fit.',
    priceUsd: 71.11,
    priceXmr: 0.43,
    category: 'adult-intimacy',
    images: [chastityCageImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rimba-pcage-pc10-penis-cage-pussy-pink'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  // Lingerie section
  {
    id: 'fits-031',
    title: 'Cottelli Collection Wetlook And Mesh Jumpsuit',
    description: 'Stunning wetlook jumpsuit with mesh panels. Zipper closure, form-fitting.',
    priceUsd: 66.00,
    priceXmr: 0.40,
    category: 'adult-intimacy',
    images: [jumpsuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('cottelli-collection-wetlook-and-mesh-jumpsuit'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-032',
    title: 'Leg Avenue Fishnet Strappy Gstring Teddy',
    description: 'Fishnet teddy with strappy details. Stretchy, one size fits most.',
    priceUsd: 46.98,
    priceXmr: 0.28,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('leg-avenue-fishnet-strappy-gstring-teddy'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-033',
    title: 'Leg Avenue Rose Lace Flair Chemise Black',
    description: 'Elegant rose lace chemise. Flared hem, plus size UK 14-18.',
    priceUsd: 30.47,
    priceXmr: 0.18,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('leg-avenue-rose-lace-flair-chemise-black-uk-14-to-18'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-034',
    title: 'Le Desir Strapless Mini Dress UK 14 to 20',
    description: 'Sexy strapless mini dress. Stretchy fabric, plus size friendly.',
    priceUsd: 21.58,
    priceXmr: 0.13,
    category: 'adult-intimacy',
    images: [teddyRedImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('le-desir-strapless-mini-dress-uk-14-to-20'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-035',
    title: 'Me You Us Latex Crotchless Panties',
    description: 'Shiny latex crotchless panties. Easy care, multiple sizes.',
    priceUsd: 11.42,
    priceXmr: 0.07,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('me-you-us-latex-crotchless-panties'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-036',
    title: 'Leather Brief With Front Chain',
    description: 'Faux leather brief with decorative chain. Adjustable, comfortable fit.',
    priceUsd: 44.44,
    priceXmr: 0.27,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('leather-brief-with-front-chain'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-037',
    title: 'Sheer Pattern Crotchless Black GString',
    description: 'Elegant sheer patterned g-string. Crotchless design, comfortable fit.',
    priceUsd: 20.32,
    priceXmr: 0.12,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('sheer-pattern-crotchless-black-gstring'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-038',
    title: 'Leg Avenue Plus Size Sheer Stockings Nude',
    description: 'Classic sheer stockings in nude. Plus size UK 14-18, comfortable waistband.',
    priceUsd: 8.88,
    priceXmr: 0.05,
    category: 'adult-intimacy',
    images: [stockingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('leg-avenue-plus-size-sheer-stockings-nude-uk-14-to-18'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-039',
    title: 'Mens Black G-String Animal Print Pouch',
    description: 'Mens g-string with animal print pouch. Stretchy straps, comfortable.',
    priceUsd: 20.32,
    priceXmr: 0.12,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('mens-black-gstring-with-black-straps-to-animal-print-pouch'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-040',
    title: 'Black Fishnet Tights With Bows',
    description: 'Fishnet tights with decorative bows. Stretchy, one size fits most.',
    priceUsd: 20.32,
    priceXmr: 0.12,
    category: 'adult-intimacy',
    images: [stockingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('black-fishnet-tights-with-bows'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-041',
    title: 'Black HoldUp Stockings With Floral Lace Top',
    description: 'Stay-up stockings with elegant lace top. Silicone grip, no garters needed.',
    priceUsd: 19.04,
    priceXmr: 0.11,
    category: 'adult-intimacy',
    images: [stockingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('black-holdup-stockings-with-floral-lace-top'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-042',
    title: 'Mens Red Pouch With Jockstraps',
    description: 'Athletic jockstrap with red pouch. Supportive, comfortable design.',
    priceUsd: 16.50,
    priceXmr: 0.10,
    category: 'adult-intimacy',
    images: [laceBodysuitImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('mens-red-pouch-with-jockstraps'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-043',
    title: 'Rimba PCage PC06 Large Black',
    description: 'Large chastity cage in black. Secure locking, comfortable for extended wear.',
    priceUsd: 71.11,
    priceXmr: 0.43,
    category: 'adult-intimacy',
    images: [chastityCageImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('rimba-pcage-pc06-large-black'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-044',
    title: 'Up Yours Finger Dildo',
    description: 'Novelty finger-shaped dildo. Flexible, body-safe silicone.',
    priceUsd: 17.77,
    priceXmr: 0.11,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('up-yours-finger-dildo'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-045',
    title: 'Cum Over Finger Dildo',
    description: 'Finger-shaped novelty dildo. Fun design, body-safe materials.',
    priceUsd: 13.96,
    priceXmr: 0.08,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('cum-over-finger-dildo'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-046',
    title: 'Thumbs Up Dildo',
    description: 'Novelty thumbs-up dildo. Unique design, flexible silicone.',
    priceUsd: 17.77,
    priceXmr: 0.11,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('thumbs-up-dildo'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-047',
    title: 'Lovetoy Pinnacle Pro Twi Flex Stretcher',
    description: 'Flexible cock ring stretcher. Comfortable design, enhances stamina.',
    priceUsd: 15.23,
    priceXmr: 0.09,
    category: 'adult-intimacy',
    images: [cockRingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('lovetoy-pinnacle-pro-twi-flex-stretcher'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-048',
    title: 'Lovetoy Pinnacle Pro Ridge Bump Stretcher',
    description: 'Textured cock ring stretcher. Ridge and bump design for extra sensation.',
    priceUsd: 13.96,
    priceXmr: 0.08,
    category: 'adult-intimacy',
    images: [cockRingsImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('lovetoy-pinnacle-pro-ridge-bump-stretcher'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-049',
    title: 'Happy Dicks Dildo With Balls 7.5 Inches',
    description: '7.5-inch realistic dildo with balls. Suction cup base, flexible.',
    priceUsd: 21.58,
    priceXmr: 0.13,
    category: 'adult-intimacy',
    images: [doubleDildoImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('happy-dicks-dildo-with-balls-7-5-inches'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-050',
    title: 'Bangers Snug Double Pussy and Ass Masturbator',
    description: 'Dual-entry masturbator with realistic textures. Soft, stretchy material.',
    priceUsd: 21.58,
    priceXmr: 0.13,
    category: 'adult-intimacy',
    images: [masturbatorImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('bangers-snug-double-pussy-and-ass-masturbator'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'fits-051',
    title: 'Clean Stream Red Enema Bulb',
    description: 'Medical-grade enema bulb in red. Easy to use, easy to clean.',
    priceUsd: 24.13,
    priceXmr: 0.15,
    category: 'adult-intimacy',
    images: [prostateMassagerImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: 0,
    fulfillment: 'referral',
    referralUrl: getProductUrl('clean-stream-red-enema-bulb'),
    ageRestricted: true,
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU'],
    sellerId: 'freak-in-the-sheets',
    createdAt: new Date().toISOString(),
  },
];

export const freakInTheSheetsSeller = {
  id: 'freak-in-the-sheets',
  displayName: 'Freak In The Sheets',
  bio: 'UK-based premium adult store. High quality products. Accepts BTC, ETH. Discreet shipping.',
  location: 'United Kingdom',
  partnerUrl: FREAK_BASE_URL,
  acceptsCrypto: ['BTC', 'ETH'],
};
