/**
 * Peptides UK - Research Peptide Listings
 * UK-based research peptide vendor accepting Bitcoin
 * Established 2012 | >98% purity | cGMP ISO9001 compliant
 * 
 * DISCLAIMER: All products sold for research purposes only.
 * Not for human consumption.
 */

import { Listing } from '../types';

// Import product images
import bpc157Img from '@/assets/peptides/puk-bpc157-5mg.jpg';
import ipamorelinImg from '@/assets/peptides/puk-ipamorelin-2mg.jpg';
import ghrp6Img from '@/assets/peptides/puk-ghrp6-5mg.jpg';
import selankImg from '@/assets/peptides/puk-selank-5mg.jpg';
import ghkCuImg from '@/assets/peptides/puk-ghk-cu-50mg.jpg';

const PEPTIDES_UK_BASE_URL = 'https://peptidesuk.com';

// GBP to USD conversion rate
const GBP_TO_USD = 1.27;
const gbpToUsd = (gbp: number): number => Math.round(gbp * GBP_TO_USD * 100) / 100;

export const peptidesUKPartnerListings: Partial<Listing>[] = [
  // === TOP SELLERS ===
  {
    id: 'puk-rec-001',
    title: 'BPC-157 5mg - Research Peptide',
    description: 'Body Protection Compound-157. Research peptide for tissue repair studies. >98% purity, HPLC verified. Includes bacteriostatic water and research guide. For research purposes only.',
    priceUsd: gbpToUsd(15.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [bpc157Img],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/bpc-157/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption. Consult appropriate regulatory authorities in your jurisdiction.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-gh-001',
    title: 'Ipamorelin 2mg - Growth Hormone Research',
    description: 'Selective growth hormone secretagogue for research. Mild and well-studied GH peptide. >98% purity with full HPLC analysis. Buy the best Quality Growth Hormone Releasing Peptide Ipamorelin in the UK.',
    priceUsd: gbpToUsd(9.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [ipamorelinImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/ipamorelin-2mg/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-gh-002',
    title: 'GHRP-6 5mg - Growth Hormone Research',
    description: 'Growth Hormone Releasing Peptide-6 for appetite and GH studies. Popular research compound with extensive scientific literature. Rated 5.00 out of 5 stars.',
    priceUsd: gbpToUsd(9.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [ghrp6Img],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/ghrp-6/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-gh-003',
    title: 'Mod GRF 1-29 2mg (CJC-1295 without DAC)',
    description: 'Growth Hormone Releasing Hormone analog for research. Modified GRF version without Drug Affinity Complex. Premium quality with COA. £13.95.',
    priceUsd: gbpToUsd(13.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [ipamorelinImg], // Using similar peptide image
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/mod-grf-1-29/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-cog-001',
    title: 'Selank 5mg - Cognitive Research Peptide',
    description: 'Synthetic peptide derived from tuftsin for anxiolytic and nootropic research. Extensively studied Russian peptide. >98% purity. Rated 4.71 out of 5.',
    priceUsd: gbpToUsd(13.95),
    category: 'health-wellness',
    subcategory: 'nootropics-cognitive',
    images: [selankImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/selank/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-cog-002',
    title: 'Semax 5mg - Cognitive Research Peptide',
    description: 'Synthetic ACTH analog for cognitive enhancement research. Popular nootropic peptide with neuroprotective properties in studies. Rated 5.00 out of 5.',
    priceUsd: gbpToUsd(15.95),
    category: 'health-wellness',
    subcategory: 'nootropics-cognitive',
    images: [selankImg], // Using similar cognitive peptide image
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/semax/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-long-001',
    title: 'Epithalon 10mg - Longevity Research Peptide',
    description: 'Epitalon/Epithalamin for longevity and telomerase research. Russian peptide studied for anti-aging properties. Premium grade synthesis. Rated 4.87 out of 5.',
    priceUsd: gbpToUsd(14.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [bpc157Img], // Using similar peptide image
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/epitalon/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-long-002',
    title: 'GHK-Cu 50mg - Copper Peptide Research',
    description: 'Glycyl-L-Histidyl-L-Lysine copper complex for skin and wound healing research. Popular in anti-aging studies. High purity synthesis. Rated 4.93 out of 5.',
    priceUsd: gbpToUsd(24.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [ghkCuImg],
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/ghk-cu/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'puk-sex-001',
    title: 'PT-141 10mg - Sexual Health Research',
    description: 'Bremelanotide for sexual arousal research. Melanocortin receptor agonist studied for libido effects in both sexes. >98% purity. Rated 4.93 out of 5. Bulk pricing available.',
    priceUsd: gbpToUsd(19.95),
    category: 'health-wellness',
    subcategory: 'peptides-research',
    images: [bpc157Img], // Using similar peptide image
    condition: 'new',
    status: 'active',
    stock: 99,
    shippingPriceUsd: gbpToUsd(4.95),
    fulfillment: 'referral',
    referralUrl: `${PEPTIDES_UK_BASE_URL}/pt-141/`,
    ageRestricted: false,
    disclaimer: 'This product is sold for research purposes only. Not for human consumption.',
    discreteShipping: true,
    shipsFrom: 'UK',
    shipsTo: ['UK', 'EU', 'US', 'CA', 'AU'],
    coaAvailable: true,
    sellerId: 'peptides-uk',
    createdAt: new Date().toISOString(),
  },
];

// Seller profile
export const peptidesUKSeller = {
  id: 'peptides-uk',
  displayName: 'Peptides UK',
  bio: 'UK-based research peptide supplier since 2012. >98% purity guaranteed. cGMP & ISO9001 compliant laboratory. HPLC and MS-UPLC testing. Accepts Bitcoin and bank transfer. Free shipping on orders over £75. All products for research purposes only.',
  location: 'United Kingdom',
  partnerUrl: PEPTIDES_UK_BASE_URL,
  acceptsCrypto: ['BTC'],
  rating: 4.9,
  reviewCount: 131,
  isVerified: true,
  established: '2012',
};

export const getPeptidesUKListings = () => peptidesUKPartnerListings;
export const isPeptidesUKListing = (listing: Partial<Listing>) => 
  listing.sellerId === 'peptides-uk';
